version: '3.8'

services:
  client:
    build:
      context: ./client  # Replace with the actual path to your client code
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - my-network

  server:
    build:
      context: ./server  # Replace with the actual path to your server code
    ports:
      - "5000:5000"
    networks:
      - my-network

  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - "90:90"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - client
      - server
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
